### ISSUE TITLE
heltec-ct62  IO0 for Button??

### ISSUE THREAD

**Issue by JohnTaipei** [mrekin/MeshtasticCustomBoards#2]
Hello Sir:
why can not use IO0 for button??
it doesn't work!!

**Comment by mrekin** [comment]
Hi) 
Which board your mean?
Provide pls more info about your problem

**Comment by JohnTaipei** [comment]
@mrekin 
heltec-ct62
it woks ok
but only button false

**Comment by mrekin** [comment]
> @mrekin 
> heltec-ct62
> it woks ok
> but only button false

I don't define user button in variant.h.
Need to fix it, give me a little time (need to fix definitions and rebuild fw). 
I'll reply here.

**Comment by JohnTaipei** [comment]
@mrekin 
yes , I saw it no define

OK , waiting for your news
Thank you very much

**Comment by mrekin** [comment]
Yep, variant included minimal definition, so I need to fill it.
Currently can't test (node in another city), so build "as is"
Re-builded latest (daily) fw, pls try.

**Comment by JohnTaipei** [comment]
@mrekin 
I saw it  button is IO0
update 2.3.16 ??

**Comment by mrekin** [comment]
![Screenshot_20240712-161341.jpg](https://github.com/user-attachments/assets/dc1de66e-409a-40e2-92b8-3ea2efabda5f)

**Comment by JohnTaipei** [comment]
@mrekin 
the button function works
https://www.facebook.com/reel/855035136682230

Thank you so much

**Comment by mrekin** [comment]
I'll fix other definitions and then close this issue ant the beginning of next week.

**Comment by joyel24** [comment]
Thanks for your support @mrekin ❤️

**Comment by JohnTaipei** [comment]
@mrekin 
I saw v2.4.1  FW
Good job
Thanks Sir

**Comment by mrekin** [comment]
> @mrekin 
> I saw v2.4.1  FW
> Good job
> Thanks Sir

Fw builds twice everyday, so future versions will be available too )
